In [2]:
import numpy as np
import pandas as pd

csv1 = pd.read_csv('E:\\yuchulidata\\production_missing_num.csv')
print(csv1)
# 数据概况的观察
print(csv1.describe())
print("\n\n\n\n")
df = csv1

    type      length            thickness  fault_flg
0      E  274.027383    40.24113135955541      False
1      D   86.319269   16.906714630016268      False
2      E  123.940388   1.0184619943950775      False
3      B  175.554886    16.41492419553766      False
4      B  244.934740   29.061080805480326      False
5      B  226.426514    39.76380137107543      False
6      C  331.637671    16.83556687876311      False
7      A  200.865444   12.184256052452268      False
8      C  276.386631   29.899611485794143      False
9      E  168.441213   1.2659187080578818      False
10     D  218.139165   33.135426544140174      False
11     E  215.178995      41.759894055925      False
12     D  218.037811   11.836329482556817      False
13     E  218.310352   39.578552506382096      False
14     D  207.823248    38.70262664958969      False
15     E  286.536920    5.375502445849498      False
16     C  239.283737    18.94182599938993      False
17     C  373.654939   11.254800760032795      False
18     E  200.111625   17.974268660683798      False
19     C  326.174734    44.30785200118088      False
20     B  157.572584   0.4094952977182832      False
21     B  150.217451     8.68243047042142      False
22     C  358.604996    25.70038793058324      False
23     C  269.006490    16.95754607182907      False
24     B  202.549369                 None      False
25     D  223.806149    19.65076599420279      False
26     B  263.844324    34.66425112689404      False
27     B  169.690602                 None      False
28     A  131.849213    4.721600725740606       True
29     E  128.989765    16.52324107337661      False
..   ...         ...                  ...        ...
970    E  256.231705   18.903365812053906      False
971    E  130.088061   0.2072495832371349      False
972    D  222.141895                 None      False
973    B  101.995503   16.678299087736093      False
974    B  282.472324     56.0587694764062      False
975    A  110.370041   11.521141881061734      False
976    D   98.469885    3.370529444508824      False
977    D  162.123466   14.590533462677731      False
978    E  144.681826   5.7697795159715275      False
979    D   88.686507   0.8104185868427923      False
980    B  284.562824   49.211789564886274      False
981    D   92.867937     8.72534892719004      False
982    B  124.860888  0.21158417667589566      False
983    C  264.130761    4.560416188960922      False
984    A  214.495849    13.37727774015289      False
985    E  148.997983   1.4065275571930946       True
986    C  200.201326    17.72738754211107      False
987    A   81.070266   15.011902339881786      False
988    D   76.937713     7.54486330289181       True
989    D  108.042637   10.690985668501584      False
990    A  123.660974     8.13695545069258      False
991    C  404.523308    51.38284064988089      False
992    D  182.252364     33.3143049103221      False
993    E  178.769891   33.035073737711926      False
994    C  224.496555   16.608346317393988       True
995    C  363.214163    48.36948254254505      False
996    D  134.773797   26.861665493072845      False
997    B  231.174985    7.087471454014727      False
998    D   81.613510    5.716271403731385      False
999    C  202.010973   35.211646979555084       True

[1000 rows x 4 columns]
            length
count  1000.000000
mean    198.707127
std      84.047902
min      75.302562
25%     134.916308
50%     184.819580
75%     242.139914
max     449.359068

In [3]:
# 属性字段数值化
df = df.replace(['A', 'B', 'C', 'D', 'E'], [1, 2, 3, 4, 5])
df = df.replace("FALSE", 0)
df = df.replace("TRUE", 1)
column2 = df

print(column2)
print("已知第24行为缺失数值的行")
print(column2[24:25])
# 缺失值的填充或删除
# 把缺失值中的None转换成np.NAN格式,str类型转为float 方便处理
column2 = column2.replace("None", np.NAN)
column2 = column2.astype(float)
print("处理结果")
column2

     type      length            thickness  fault_flg
0       5  274.027383    40.24113135955541      False
1       4   86.319269   16.906714630016268      False
2       5  123.940388   1.0184619943950775      False
3       2  175.554886    16.41492419553766      False
4       2  244.934740   29.061080805480326      False
5       2  226.426514    39.76380137107543      False
6       3  331.637671    16.83556687876311      False
7       1  200.865444   12.184256052452268      False
8       3  276.386631   29.899611485794143      False
9       5  168.441213   1.2659187080578818      False
10      4  218.139165   33.135426544140174      False
11      5  215.178995      41.759894055925      False
12      4  218.037811   11.836329482556817      False
13      5  218.310352   39.578552506382096      False
14      4  207.823248    38.70262664958969      False
15      5  286.536920    5.375502445849498      False
16      3  239.283737    18.94182599938993      False
17      3  373.654939   11.254800760032795      False
18      5  200.111625   17.974268660683798      False
19      3  326.174734    44.30785200118088      False
20      2  157.572584   0.4094952977182832      False
21      2  150.217451     8.68243047042142      False
22      3  358.604996    25.70038793058324      False
23      3  269.006490    16.95754607182907      False
24      2  202.549369                 None      False
25      4  223.806149    19.65076599420279      False
26      2  263.844324    34.66425112689404      False
27      2  169.690602                 None      False
28      1  131.849213    4.721600725740606       True
29      5  128.989765    16.52324107337661      False
..    ...         ...                  ...        ...
970     5  256.231705   18.903365812053906      False
971     5  130.088061   0.2072495832371349      False
972     4  222.141895                 None      False
973     2  101.995503   16.678299087736093      False
974     2  282.472324     56.0587694764062      False
975     1  110.370041   11.521141881061734      False
976     4   98.469885    3.370529444508824      False
977     4  162.123466   14.590533462677731      False
978     5  144.681826   5.7697795159715275      False
979     4   88.686507   0.8104185868427923      False
980     2  284.562824   49.211789564886274      False
981     4   92.867937     8.72534892719004      False
982     2  124.860888  0.21158417667589566      False
983     3  264.130761    4.560416188960922      False
984     1  214.495849    13.37727774015289      False
985     5  148.997983   1.4065275571930946       True
986     3  200.201326    17.72738754211107      False
987     1   81.070266   15.011902339881786      False
988     4   76.937713     7.54486330289181       True
989     4  108.042637   10.690985668501584      False
990     1  123.660974     8.13695545069258      False
991     3  404.523308    51.38284064988089      False
992     4  182.252364     33.3143049103221      False
993     5  178.769891   33.035073737711926      False
994     3  224.496555   16.608346317393988       True
995     3  363.214163    48.36948254254505      False
996     4  134.773797   26.861665493072845      False
997     2  231.174985    7.087471454014727      False
998     4   81.613510    5.716271403731385      False
999     3  202.010973   35.211646979555084       True

[1000 rows x 4 columns]
已知第24行为缺失数值的行
    type      length thickness  fault_flg
24     2  202.549369      None      False
处理结果

     type      length  thickness  fault_flg
0     5.0  274.027383  40.241131        0.0
1     4.0   86.319269  16.906715        0.0
2     5.0  123.940388   1.018462        0.0
3     2.0  175.554886  16.414924        0.0
4     2.0  244.934740  29.061081        0.0
5     2.0  226.426514  39.763801        0.0
6     3.0  331.637671  16.835567        0.0
7     1.0  200.865444  12.184256        0.0
8     3.0  276.386631  29.899611        0.0
9     5.0  168.441213   1.265919        0.0
10    4.0  218.139165  33.135427        0.0
11    5.0  215.178995  41.759894        0.0
12    4.0  218.037811  11.836329        0.0
13    5.0  218.310352  39.578553        0.0
14    4.0  207.823248  38.702627        0.0
15    5.0  286.536920   5.375502        0.0
16    3.0  239.283737  18.941826        0.0
17    3.0  373.654939  11.254801        0.0
18    5.0  200.111625  17.974269        0.0
19    3.0  326.174734  44.307852        0.0
20    2.0  157.572584   0.409495        0.0
21    2.0  150.217451   8.682430        0.0
22    3.0  358.604996  25.700388        0.0
23    3.0  269.006490  16.957546        0.0
24    2.0  202.549369        NaN        0.0
25    4.0  223.806149  19.650766        0.0
26    2.0  263.844324  34.664251        0.0
27    2.0  169.690602        NaN        0.0
28    1.0  131.849213   4.721601        1.0
29    5.0  128.989765  16.523241        0.0
..    ...         ...        ...        ...
970   5.0  256.231705  18.903366        0.0
971   5.0  130.088061   0.207250        0.0
972   4.0  222.141895        NaN        0.0
973   2.0  101.995503  16.678299        0.0
974   2.0  282.472324  56.058769        0.0
975   1.0  110.370041  11.521142        0.0
976   4.0   98.469885   3.370529        0.0
977   4.0  162.123466  14.590533        0.0
978   5.0  144.681826   5.769780        0.0
979   4.0   88.686507   0.810419        0.0
980   2.0  284.562824  49.211790        0.0
981   4.0   92.867937   8.725349        0.0
982   2.0  124.860888   0.211584        0.0
983   3.0  264.130761   4.560416        0.0
984   1.0  214.495849  13.377278        0.0
985   5.0  148.997983   1.406528        1.0
986   3.0  200.201326  17.727388        0.0
987   1.0   81.070266  15.011902        0.0
988   4.0   76.937713   7.544863        1.0
989   4.0  108.042637  10.690986        0.0
990   1.0  123.660974   8.136955        0.0
991   3.0  404.523308  51.382841        0.0
992   4.0  182.252364  33.314305        0.0
993   5.0  178.769891  33.035074        0.0
994   3.0  224.496555  16.608346        1.0
995   3.0  363.214163  48.369483        0.0
996   4.0  134.773797  26.861665        0.0
997   2.0  231.174985   7.087471        0.0
998   4.0   81.613510   5.716271        0.0
999   3.0  202.010973  35.211647        1.0

[1000 rows x 4 columns]

In [5]:
# 使用常数填充
# 将所有的None换成0
column3 = column2.fillna(0)
print("使用常数法填充后的24行")
print(column3[24:25])
# 统计缺省值NaN的个数
column2.isnull().sum()

使用常数法填充后的24行
    type      length  thickness  fault_flg
24   2.0  202.549369        0.0        0.0

type           0
length         0
thickness    108
fault_flg      0
dtype: int64

In [4]:
# 求这一行的聚合值
column2_mean = column2.mean()
print(column2_mean)
# 使用平均数填充
column3 = column2.fillna(column2_mean)
print("使用平均数填充后的24行")
print(column3[24:25])

type           3.030000
length       198.707127
thickness     19.470386
fault_flg      0.052000
dtype: float64
使用平均数填充后的24行
    type      length  thickness  fault_flg
24   2.0  202.549369  19.470386        0.0

In [8]:
column2_mid = column2.median()
print(column2_mid)
# 使用中位数填充
column3 = column2.fillna(column2_mid)
print(column3[24:25])

type           3.000000
length       184.819580
thickness     16.902018
fault_flg      0.000000
dtype: float64
    type      length  thickness  fault_flg
24   2.0  202.549369  16.902018        0.0

In [6]:
# c2std = column2.std()
# topnum1 =column2_mean+2*c2std
# bottomnum1 = column2_mean-2*c2std

# print("正常值的范围：",topnum1,bottomnum1)

# print("是否存在超出正常范围的值：",any(column2>topnum1))
# print("是否存在小于正常范围的值：",any(column2<bottomnum1))
# print("异常值如下")
# column2[column2>topnum1]
# column2[column2<bottomnum1]

正常值的范围： type           5.849282
length       366.802931
thickness     48.868554
fault_flg      0.496276
dtype: float64 type          0.210718
length       30.611324
thickness    -9.927782
fault_flg    -0.392276
dtype: float64
是否存在超出正常范围的值： True
是否存在小于正常范围的值： True
异常值如下

     type  length  thickness  fault_flg
0     NaN     NaN        NaN        NaN
1     NaN     NaN        NaN        NaN
2     NaN     NaN        NaN        NaN
3     NaN     NaN        NaN        NaN
4     NaN     NaN        NaN        NaN
..    ...     ...        ...        ...
995   NaN     NaN        NaN        NaN
996   NaN     NaN        NaN        NaN
997   NaN     NaN        NaN        NaN
998   NaN     NaN        NaN        NaN
999   NaN     NaN        NaN        NaN

[1000 rows x 4 columns]

In [9]:
zscore = (column3 - column3.mean()) / column3.std()
zscore_r = zscore[abs(zscore) <= 3]
print(zscore_r)

normalized = zscore_r / (zscore_r.max() - zscore_r.min())
print("____________________")
normalized["fault_flg"] = column2["fault_flg"]
normalized

         type    length  thickness  fault_flg
0    1.397519  0.896159   1.513741  -0.234089
1    0.688119 -1.337188  -0.164425  -0.234089
2    1.397519 -0.889573  -1.307078  -0.234089
3   -0.730683 -0.275465  -0.199794  -0.234089
4   -0.730683  0.550015   0.709693  -0.234089
..        ...       ...        ...        ...
995 -0.021282  1.957301   2.098316  -0.234089
996  0.688119 -0.760677   0.551515  -0.234089
997 -0.730683  0.386302  -0.870606  -0.234089
998  0.688119 -1.393177  -0.969220  -0.234089
999 -0.021282  0.039309   1.152030        NaN

[1000 rows x 4 columns]
____________________

       type    length  thickness  fault_flg
0    0.4925  0.201361   0.346542        0.0
1    0.2425 -0.300457  -0.037642        0.0
2    0.4925 -0.199881  -0.299231        0.0
3   -0.2575 -0.061895  -0.045739        0.0
4   -0.2575  0.123585   0.162471        0.0
..      ...       ...        ...        ...
995 -0.0075  0.439792   0.480370        0.0
996  0.2425 -0.170919   0.126259        0.0
997 -0.2575  0.086799  -0.199309        0.0
998  0.2425 -0.313037  -0.221885        0.0
999 -0.0075  0.008832   0.263735        1.0

[1000 rows x 4 columns]

In [23]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)

normalized = normalized.dropna()
normalized.isna().sum()
pca.fit_transform(normalized)

array([[-5.24087848e-01,  3.37667009e-01,  9.99443525e-02],
       [-2.16195424e-01, -2.20238832e-01, -1.27429366e-01],
       [-4.61189149e-01, -3.33108585e-01, -1.98716147e-01],
       ...,
       [ 2.57294090e-01, -9.46291143e-03, -8.36031804e-02],
       [-2.06611611e-01, -3.41629426e-01, -1.90732320e-01],
       [-6.50259531e-04, -1.83757803e-01,  9.64215567e-01]])

In [9]:

# column3 = column2.dropna()
# print(column3)

0       40.24113135955541
1      16.906714630016268
2      1.0184619943950775
3       16.41492419553766
4      29.061080805480326
              ...
995     48.36948254254505
996    26.861665493072845
997     7.087471454014727
998     5.716271403731385
999    35.211646979555084
Name: thickness, Length: 892, dtype: object